function band_stop_ex1 = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 23.2 and Signal Processing Toolbox 23.2.
% Generated on: 07-May-2024 14:43:54

persistent Hd;

if isempty(Hd)
    
    Fpass1 = 0.35;  % First Passband Frequency
    Fstop1 = 0.4;   % First Stopband Frequency
    Fstop2 = 0.6;   % Second Stopband Frequency
    Fpass2 = 0.65;  % Second Passband Frequency
    Apass1 = 1;     % First Passband Ripple (dB)
    Astop  = 100;   % Stopband Attenuation (dB)
    Apass2 = 1;     % Second Passband Ripple (dB)
    
    h = fdesign.bandstop('fp1,fst1,fst2,fp2,ap1,ast,ap2', Fpass1, Fstop1, ...
        Fstop2, Fpass2, Apass1, Astop, Apass2);
    
    Hd = design(h, 'ellip', ...
        'MatchExactly', 'both');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

band_stop_ex1 = filter(Hd,x);

