function y = doFilter(x)
%DOFILTER Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 23.2 and Signal Processing Toolbox 23.2.
% Generated on: 07-May-2024 16:10:49

persistent Hd;

if isempty(Hd)
    
    N     = 20;   % Order
    F3dB1 = 0.4;  % First
    F3dB2 = 0.6;  % Second
    
    h = fdesign.bandpass('n,f3db1,f3db2', N, F3dB1, F3dB2);
    
    Hd = design(h, 'butter');
    
    
    
    set(Hd,'PersistentMemory',true);
    
end

y = filter(Hd,x);

