function Hd = ex12_2_bandpass_filteroutput
%GETFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 23.2 and Signal Processing Toolbox 23.2.
% Generated on: 07-May-2024 16:13:52

Fstop1 = 0.35;  % First Stopband Frequency
Fpass1 = 0.45;  % First Passband Frequency
Fpass2 = 0.55;  % Second Passband Frequency
Fstop2 = 0.65;  % Second Stopband Frequency
Astop1 = 60;    % First Stopband Attenuation (dB)
Apass  = 1;     % Passband Ripple (dB)
Astop2 = 60;    % Second Stopband Attenuation (dB)

h = fdesign.bandpass('fst1,fp1,fp2,fst2,ast1,ap,ast2', Fstop1, Fpass1, ...
    Fpass2, Fstop2, Astop1, Apass, Astop2);

Hd = design(h, 'ellip', ...
    'MatchExactly', 'both');


